ga_params:
  Kbest: 5
  population: 100
  init_sched_percent: 0.05
  crossover_probability: 0.4
  replacing_mutation_probability: 0.2
  sweep_mutation_probability: 0.3
  generations: 25

wf_name: "Montage_25"