from environment.Utility import Utility
from reschedulingheft.HeftHelper import HeftHelper


def main():
    ## 0. create reliability

    ##======================
    ## Load generated by GA schedule and resource config
    ##======================
    wf_name = "CyberShake_30"

    dax1 = '..\\..\\resources\\' + wf_name + '.xml'
    ##dax1 = '..\\..\\resources\\Montage_50.xml'
    wf_start_id_1 = "00"
    task_postfix_id_1 = "00"
    deadline_1 = 1000

    wf = Utility.readWorkflow(dax1, wf_start_id_1, task_postfix_id_1, deadline_1)
    name = wf_name + "_bundle"
    path = '..\\..\\resources\\saved_schedules\\' + name + '.json'
    bundle = Utility.load_schedule(path, wf)

    ##======================
    ## create realibility
    ##======================
    nodes = HeftHelper.to_nodes(bundle.dedicated_resources)
    ## give 100% to all
    realibility_map = { node.id: 1 for node in nodes}
    ## choose one node and give 75% to it
    selected_node = nodes[1]
    realibility_map[selected_node.id] = 0.75

    ##======================
    ## create ga_executor
    ##======================

    ## 1. obtain ga_schedule
    ## 2. create ga_executor and run experiment there
    ## 3. run 5 times

    ## 3. create heft_executor and run experiment there
    ## 4. run 5 times

    ## 5. compare static ga vs dynamic-ga vs dynamic-heft
    pass

main()
