from GA.DEAPGA.GAExecutor import GAExecutor, TaskFinished
from environment.EventAutomata import EventAutomata
from environment.Utility import Utility
from core.HeftHelper import HeftHelper
from core.concrete_realization import ExperimentEstimator, ExperimentResourceManager


def main():
    ## 0. create reliability

    ##======================
    ## Load generated by GA schedule and resource config
    ##======================
    wf_name = "CyberShake_30"

    dax1 = '..\\..\\resources\\' + wf_name + '.xml'
    ##dax1 = '..\\..\\resources\\Montage_50.xml'
    wf_start_id_1 = "00"
    task_postfix_id_1 = "00"
    deadline_1 = 1000

    wf = Utility.readWorkflow(dax1, wf_start_id_1, task_postfix_id_1, deadline_1)
    name = wf_name + "_bundle"
    path = '..\\..\\resources\\saved_schedules\\' + name + '.json'
    bundle = Utility.load_schedule(path, wf)

    ##======================
    ## create realibility
    ##======================
    nodes = HeftHelper.to_nodes(bundle.dedicated_resources)
    ## give 100% to all
    realibility_map = { node.name: 1 for node in nodes}
    ## choose one node and give 75% to it
    selected_node = list(nodes)[1]
    realibility_map[selected_node.name] = 0.75

    ##======================
    ## create ga_executor
    ##======================
    estimator = ExperimentEstimator(bundle.transfer_mx, bundle.ideal_flops, realibility_map)
    resource_manager = ExperimentResourceManager(bundle.dedicated_resources)
    ga_executor = GAExecutor(initial_schedule=bundle.ga_schedule,
                             estimator=estimator,
                             resource_manager=resource_manager,
                             base_fail_duration=30,
                             base_fail_dispersion=10)

    automata = EventAutomata(ga_executor)

    event = TaskFinished()
    event.time_posted = 0
    event.time_happened = 0
    event.task = wf.head_task
    event.node = None
    automata.post(event)

    automata.run()

    dynamic_ga_makespan = Utility.get_the_last_time(ga_executor.schedule)
    seq_time_validaty = Utility.validateNodesSeq(ga_executor.schedule)
    dependency_validaty = Utility.validateParentsAndChildren(ga_executor.schedule, wf)
    ##periods_validaty = Utility.validateUnavailabilityPeriods(ga_executor.schedule, unavailability_periods)
    print("heft_makespan: " + str(dynamic_ga_makespan))
    print("=============Res Results====================")
    print("              Makespan %s" % str(dynamic_ga_makespan))
    print("          Seq validaty %s" % str(seq_time_validaty))
    print("   Dependancy validaty %s" % str(dependency_validaty))
    ##print("      Periods validaty %s" % str(periods_validaty))

    ## 1. obtain ga_schedule
    ## 2. create ga_executor and run experiment there
    ## 3. run 5 times

    ## 3. create heft_executor and run experiment there
    ## 4. run 5 times

    ## 5. compare static ga vs dynamic-ga vs dynamic-heft
    pass

main()
