from heft.core.environment.ResourceManager import Estimator
from heft.core.environment.ResourceManager import ResourceManager


class ExperimentEstimator(Estimator):
    def __init__(self, transferMx, ideal_flops, reliability=1.0, transfer_time=100):
        self.transfer_matrix = transferMx
        self.cache = dict()
        self.ideal_flops = ideal_flops
        self.reliability = reliability
        self.transfer_time = transfer_time

    # #get estimated time of running the task on the node
    def estimate_runtime(self, task, node):
        result = (task.runtime * self.ideal_flops) / node.flops
        ##print("estimate: " + str(result))
        return result

    ## estimate transfer time between node1 and node2 for data generated by the task
    def estimate_transfer_time(self, node1, node2, task1, task2):
        ##TODO: remake it later
        if node1 == node2:
            return 0
        return self.transfer_time
        ##TODO: repair it later
        ##per_unit_of_time = 1##self.transfer_matrix[node1][node2]
        ##return self.get_or_estimate(task1, task2)/per_unit_of_time

    def get_or_estimate(self, task1, task2):
        if self.cache.get(task1, None) is not None:
            if self.cache[task1].get(task2, None) is not None:
                return self.cache[task1][task2]
            else:
                self.cache[task1][task2] = None
        else:
            self.cache[task1] = {task2: None}

        def get_transfer_time(name):
            file = task1.output_files.get(name, None)
            return 0 if file is None else file.size

        lst = [get_transfer_time(name) for (name, file) in task2.input_files.items()]
        result = sum(lst)
        self.cache[task1][task2] = result
        return result

    ## estimate probability of successful ending of the task on the node
    def estimate_reliability(self, task, node):
        return self.reliability[node.name]


class ExperimentResourceManager(ResourceManager):

    def setVMParameter(self, farm_capacity, max_resource_capacity):
        self.farm_capacity = farm_capacity
        self.max_resource_capacity = max_resource_capacity
        pass

    def __init__(self, resources):
        self.resources = resources
        self.resources_map = {res.name: res for res in self.resources}
        self._name_to_node = None

    # # TODO: fix problem with id
    def node(self, node):
        result = [nd for nd in self.resources_map[node.resource.name].nodes if nd.name == node.name]
        if len(result) == 0:
            return None
        return result[0]

    ##get all resources in the system
    def get_resources(self):
        return self.resources

    def change_performance(self, node, performance):
        ##TODO: rethink it
        self.resources[node.resource][node].flops = performance

    def byName(self, name):
        if self._name_to_node is None:
            self._name_to_node = {n.name: n for n in self.get_nodes()}
        return self._name_to_node.get(name, None)



